[package]
name = "lang-lexer"
version = "0.1.7"
license-file = "../LICENSE"
edition = "2021"

[features]
default = ["comment", "delimiter"]
comment = []
delimiter = []

[lib]
path = "./lib.rs"

[dependencies]
codepoints = { path = "../codepoints", package = "lang-codepoints" }
location = { path = "../location", package = "lang-location" }
stream = { path = "../stream", package = "lang-stream" }
